builds:
 - main: "cmd/funcguard/main.go"
   env:
    - CGO_ENABLED=0
   goos:
    - freebsd
    - windows
    - linux
    - darwin
   goarch:
    - amd64
    - arm
    - arm64

archives:
 - format: tar.gz
   name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
   format_overrides:
    - goos: windows
      format: zip
   files:
    - 'NONE*'
checksum:
 name_template: 'checksums.txt'
snapshot:
 name_template: "{{ incpatch .Version }}-next"
changelog:
 skip: false
 sort: asc
 filters:
  exclude:
   - '^docs:'
   - '^test:'
release:
 draft: true

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
